image_input_topic: "/bebop/image_raw"
face_detected_image_topic: "/face_detector/raw_image"
haar_file_face: "/home/robond/catkin_ws/src/face_tracker_pkg/data/face.xml"
face_tracking: 1
display_original_image: 1
display_tracking_image: 1
